version: '3.8'

services:
  memcached:
    image: memcached:latest
    container_name: misc-tests-memcached
    ports:
      - "11211:11211"
    command: ["memcached", "-m", "64", "-c", "1024"]
  redis:
    image: redis:6.2-alpine
    container_name: misc-tests-redis
    command: redis-server --requirepass mypass
    volumes:
      - misc-tests-redis-cache:/data
    ports:
      - "6379:6379"

volumes:
  misc-tests-redis-cache:
