spring:
  main:
    lazy-initialization: false
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  application:
    name: ${APPLICATION_NAME:MiscDefault}
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.globally_quoted_identifiers: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true

cache:
  memcached:
    host: localhost
    port: 11211
    # 0 (infinite) -> X in seconds
    defaultTTL: 0
    timeout: 500
    # none, inmemory, memcached
    mode: memcached
  redis:
    host: localhost
    port: 6379
    password: mypass
    # -1 (infinite) -> X in seconds
    defaultTTL: -1
    timeout: 500
    # none, inmemory, redis
    mode: redis
  caffeine:
    # -1 (infinite) -> X in seconds
    defaultTTL: -1
    # none, caffeine
    mode: caffeine

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR